# Generated by Django 4.0.5 on 2022-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=40)),
                ('puesto', models.CharField(max_length=40)),
                ('fechaInicial', models.CharField(max_length=40)),
                ('fechaFinal', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=400)),
                ('referencia', models.CharField(max_length=40)),
                ('telefonoReferencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=40)),
                ('nombreCurso', models.CharField(max_length=50)),
                ('fechaInicial', models.CharField(max_length=40)),
                ('fechaFinal', models.CharField(max_length=40)),
                ('proyectoFinal', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=40)),
                ('nivel', models.CharField(max_length=40)),
            ],
        ),
    ]
